import { Link } from 'react-router-dom';
import { Zap } from 'lucide-react';
import { motion } from 'framer-motion';

export default function Terms() {
  return (
    <div className="min-h-screen bg-background text-white bg-hero-pattern bg-cover bg-center bg-no-repeat bg-fixed relative">
      <div className="absolute inset-0 bg-background/90 backdrop-blur-md" />
      
      <div className="relative z-10">
        <header className="container mx-auto px-6 py-6 flex justify-between items-center glass sticky top-0 z-50 rounded-b-2xl mb-12">
          <Link to="/" className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-primary to-secondary flex items-center justify-center">
              <Zap className="w-6 h-6 text-white" />
            </div>
            <h1 className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-primary to-secondary">
              Velocity AI
            </h1>
          </Link>
          <nav className="flex gap-6 items-center">
            <Link to="/docs" className="text-gray-300 hover:text-white transition-colors">Documentation</Link>
            <Link to="/privacy" className="text-gray-300 hover:text-white transition-colors">Privacy Policy</Link>
            <Link to="/auth" className="px-6 py-2 rounded-lg bg-white/10 hover:bg-white/20 border border-white/20 transition-all font-medium">
              Sign In
            </Link>
          </nav>
        </header>

        <main className="container mx-auto px-6 py-12 pb-32 max-w-4xl">
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="glass p-8 md:p-12 rounded-3xl"
          >
            <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
            <div className="space-y-8 text-gray-300 leading-relaxed">
              
              <section>
                <h2 className="text-2xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
                <p>By accessing, downloading, or using the Velocity AI command-line interface ("CLI"), website, or associated services (collectively, the "Services"), you agree to be bound by these Terms of Service. If you do not agree to these terms, you must not use our Services. These terms constitute a legally binding agreement between you and the developers of Velocity AI.</p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-white mb-4">2. Description of Service</h2>
                <p>Velocity AI is an advanced terminal-based AI assistant designed to help developers with coding, debugging, and general software development tasks directly within their command line environment. The Service interacts with third-party Large Language Models (LLMs) (e.g., Mistral, OpenAI) to process your queries and provide responses.</p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-white mb-4">3. User Accounts and Authentication</h2>
                <p>To access certain features of the CLI, you must create an account. You are responsible for maintaining the confidentiality of your account credentials, including the session tokens generated by the CLI. You agree to immediately notify us of any unauthorized use of your account. We are not liable for any loss or damage arising from your failure to protect your credentials.</p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-white mb-4">4. Acceptable Use Policy</h2>
                <p>You agree not to use the Services to:</p>
                <ul className="list-disc pl-6 mt-4 space-y-2">
                  <li>Violate any applicable laws, regulations, or third-party rights.</li>
                  <li>Attempt to bypass, disable, or interfere with security-related features of the Services.</li>
                  <li>Engage in automated scraping, data harvesting, or denial-of-service attacks against our servers.</li>
                  <li>Use the AI models provided through the CLI for malicious purposes, including generating harmful, illegal, or abusive content.</li>
                  <li>Reverse engineer, decompile, or disassemble any portion of the software, except where permitted by applicable law.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-white mb-4">5. API Usage and Rate Limiting</h2>
                <p>The free tier of Velocity AI provides access to the Velocity Large (Mistral) model subject to strict rate limits (e.g., 6 messages per 8 hours). You agree not to circumvent these limits. If you utilize your own API keys for third-party providers (e.g., OpenAI, Anthropic), you are solely responsible for any charges incurred on those platforms resulting from your use of the Velocity AI CLI.</p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-white mb-4">6. Intellectual Property</h2>
                <p>All rights, title, and interest in and to the Services (excluding content provided by you and responses generated by third-party LLMs) are and will remain the exclusive property of Velocity AI and its licensors. The software is provided for your personal or internal business use only.</p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-white mb-4">7. Disclaimer of Warranties</h2>
                <p>THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DO NOT GUARANTEE THAT THE AI-GENERATED CODE OR RESPONSES WILL BE ERROR-FREE, SECURE, OR ACCURATE. YOU ARE SOLELY RESPONSIBLE FOR REVIEWING AND TESTING ANY CODE SUGGESTED BY VELOCITY AI BEFORE DEPLOYING IT.</p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-white mb-4">8. Limitation of Liability</h2>
                <p>IN NO EVENT SHALL VELOCITY AI, ITS DEVELOPERS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICES.</p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-white mb-4">9. Changes to Terms</h2>
                <p>We reserve the right to modify these terms at any time. We will notify you of any material changes by posting the new Terms of Service on this page. Your continued use of the Services after any such changes constitutes your acceptance of the new Terms of Service.</p>
              </section>

              <p className="pt-8 border-t border-white/10 text-sm">Last Updated: August 2026</p>
            </div>
          </motion.div>
        </main>

        <footer className="border-t border-white/10 bg-black/40 backdrop-blur-md py-12 mt-20">
          <div className="container mx-auto px-6">
            <div className="flex flex-col md:flex-row justify-between items-center gap-6">
              <div className="flex items-center gap-2">
                <Zap className="w-5 h-5 text-primary" />
                <span className="text-xl font-bold text-white">Velocity AI</span>
              </div>
              <div className="flex gap-6 text-sm text-gray-400">
                <Link to="/docs" className="hover:text-white transition-colors">Documentation</Link>
                <Link to="/terms" className="hover:text-white transition-colors">Terms of Service</Link>
                <Link to="/privacy" className="hover:text-white transition-colors">Privacy Policy</Link>
              </div>
              <div className="text-sm text-gray-500">
                &copy; {new Date().getFullYear()} Velocity AI. All rights reserved.
              </div>
            </div>
          </div>
        </footer>
      </div>
    </div>
  );
}
